/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter16_Tick.h"
#include "EzI2Cs.h"
#include "PWM8_LeftFwd.h"
#include "PWM8_LeftRev.h"
#include "PWM8_Pump.h"
#include "PWM8_RightFwd.h"
#include "PWM8_RightRev.h"
#include "SAR10.h"
#include "SleepTimer.h"

#endif
