//*****************************************************************************
//*****************************************************************************
//  FILENAME: Counter8_3.h
//   Version: 2.60, Updated on 2012/3/2 at 9:13:11
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Counter8_3_INCLUDE
#define Counter8_3_INCLUDE

#include <m8c.h>

#pragma fastcall16 Counter8_3_EnableInt
#pragma fastcall16 Counter8_3_DisableInt
#pragma fastcall16 Counter8_3_Start
#pragma fastcall16 Counter8_3_Stop
#pragma fastcall16 Counter8_3_bReadCounter              // Read  DR0
#pragma fastcall16 Counter8_3_WritePeriod               // Write DR1
#pragma fastcall16 Counter8_3_bReadCompareValue         // Read  DR2
#pragma fastcall16 Counter8_3_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bCounter8_3_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bCounter8_3_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Counter8_3 API.
//-------------------------------------------------

extern void Counter8_3_EnableInt(void);                           // Proxy Class 1
extern void Counter8_3_DisableInt(void);                          // Proxy Class 1
extern void Counter8_3_Start(void);                               // Proxy Class 1
extern void Counter8_3_Stop(void);                                // Proxy Class 1
extern BYTE Counter8_3_bReadCounter(void);                        // Proxy Class 1
extern void Counter8_3_WritePeriod(BYTE bPeriod);                 // Proxy Class 1
extern BYTE Counter8_3_bReadCompareValue(void);                   // Proxy Class 2
extern void Counter8_3_WriteCompareValue(BYTE bCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bCounter8_3_ReadCounter(void);            // Deprecated
extern BYTE bCounter8_3_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for Counter8_3 API's.
//--------------------------------------------------

#define Counter8_3_CONTROL_REG_START_BIT       ( 0x01 )
#define Counter8_3_INT_REG_ADDR                ( 0x0e1 )
#define Counter8_3_INT_MASK                    ( 0x40 )


//--------------------------------------------------
// Constants for Counter8_3 user defined values
//--------------------------------------------------

#define Counter8_3_PERIOD                      ( 0x00 )
#define Counter8_3_COMPARE_VALUE               ( 0x00 )


//-------------------------------------------------
// Register Addresses for Counter8_3
//-------------------------------------------------

#pragma ioport  Counter8_3_COUNTER_REG: 0x038              //DR0 Count register
BYTE            Counter8_3_COUNTER_REG;
#pragma ioport  Counter8_3_PERIOD_REG:  0x039              //DR1 Period register
BYTE            Counter8_3_PERIOD_REG;
#pragma ioport  Counter8_3_COMPARE_REG: 0x03a              //DR2 Compare register
BYTE            Counter8_3_COMPARE_REG;
#pragma ioport  Counter8_3_CONTROL_REG: 0x03b              //Control register
BYTE            Counter8_3_CONTROL_REG;
#pragma ioport  Counter8_3_FUNC_REG:    0x138              //Function register
BYTE            Counter8_3_FUNC_REG;
#pragma ioport  Counter8_3_INPUT_REG:   0x139              //Input register
BYTE            Counter8_3_INPUT_REG;
#pragma ioport  Counter8_3_OUTPUT_REG:  0x13a              //Output register
BYTE            Counter8_3_OUTPUT_REG;
#pragma ioport  Counter8_3_INT_REG:       0x0e1            //Interrupt Mask Register
BYTE            Counter8_3_INT_REG;


//-------------------------------------------------
// Counter8_3 Macro 'Functions'
//-------------------------------------------------

#define Counter8_3_Start_M \
   Counter8_3_CONTROL_REG |=  Counter8_3_CONTROL_REG_START_BIT

#define Counter8_3_Stop_M  \
   Counter8_3_CONTROL_REG &= ~Counter8_3_CONTROL_REG_START_BIT

#define Counter8_3_EnableInt_M   \
   M8C_EnableIntMask(Counter8_3_INT_REG, Counter8_3_INT_MASK)

#define Counter8_3_DisableInt_M  \
   M8C_DisableIntMask(Counter8_3_INT_REG, Counter8_3_INT_MASK)

#endif
// end of file Counter8_3.h
