//*****************************************************************************
//*****************************************************************************
//  FILENAME: Counter8_4.h
//   Version: 2.60, Updated on 2012/3/2 at 9:13:11
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Counter8_4_INCLUDE
#define Counter8_4_INCLUDE

#include <m8c.h>

#pragma fastcall16 Counter8_4_EnableInt
#pragma fastcall16 Counter8_4_DisableInt
#pragma fastcall16 Counter8_4_Start
#pragma fastcall16 Counter8_4_Stop
#pragma fastcall16 Counter8_4_bReadCounter              // Read  DR0
#pragma fastcall16 Counter8_4_WritePeriod               // Write DR1
#pragma fastcall16 Counter8_4_bReadCompareValue         // Read  DR2
#pragma fastcall16 Counter8_4_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bCounter8_4_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bCounter8_4_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Counter8_4 API.
//-------------------------------------------------

extern void Counter8_4_EnableInt(void);                           // Proxy Class 1
extern void Counter8_4_DisableInt(void);                          // Proxy Class 1
extern void Counter8_4_Start(void);                               // Proxy Class 1
extern void Counter8_4_Stop(void);                                // Proxy Class 1
extern BYTE Counter8_4_bReadCounter(void);                        // Proxy Class 1
extern void Counter8_4_WritePeriod(BYTE bPeriod);                 // Proxy Class 1
extern BYTE Counter8_4_bReadCompareValue(void);                   // Proxy Class 2
extern void Counter8_4_WriteCompareValue(BYTE bCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bCounter8_4_ReadCounter(void);            // Deprecated
extern BYTE bCounter8_4_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for Counter8_4 API's.
//--------------------------------------------------

#define Counter8_4_CONTROL_REG_START_BIT       ( 0x01 )
#define Counter8_4_INT_REG_ADDR                ( 0x0e1 )
#define Counter8_4_INT_MASK                    ( 0x80 )


//--------------------------------------------------
// Constants for Counter8_4 user defined values
//--------------------------------------------------

#define Counter8_4_PERIOD                      ( 0x00 )
#define Counter8_4_COMPARE_VALUE               ( 0x00 )


//-------------------------------------------------
// Register Addresses for Counter8_4
//-------------------------------------------------

#pragma ioport  Counter8_4_COUNTER_REG: 0x03c              //DR0 Count register
BYTE            Counter8_4_COUNTER_REG;
#pragma ioport  Counter8_4_PERIOD_REG:  0x03d              //DR1 Period register
BYTE            Counter8_4_PERIOD_REG;
#pragma ioport  Counter8_4_COMPARE_REG: 0x03e              //DR2 Compare register
BYTE            Counter8_4_COMPARE_REG;
#pragma ioport  Counter8_4_CONTROL_REG: 0x03f              //Control register
BYTE            Counter8_4_CONTROL_REG;
#pragma ioport  Counter8_4_FUNC_REG:    0x13c              //Function register
BYTE            Counter8_4_FUNC_REG;
#pragma ioport  Counter8_4_INPUT_REG:   0x13d              //Input register
BYTE            Counter8_4_INPUT_REG;
#pragma ioport  Counter8_4_OUTPUT_REG:  0x13e              //Output register
BYTE            Counter8_4_OUTPUT_REG;
#pragma ioport  Counter8_4_INT_REG:       0x0e1            //Interrupt Mask Register
BYTE            Counter8_4_INT_REG;


//-------------------------------------------------
// Counter8_4 Macro 'Functions'
//-------------------------------------------------

#define Counter8_4_Start_M \
   Counter8_4_CONTROL_REG |=  Counter8_4_CONTROL_REG_START_BIT

#define Counter8_4_Stop_M  \
   Counter8_4_CONTROL_REG &= ~Counter8_4_CONTROL_REG_START_BIT

#define Counter8_4_EnableInt_M   \
   M8C_EnableIntMask(Counter8_4_INT_REG, Counter8_4_INT_MASK)

#define Counter8_4_DisableInt_M  \
   M8C_DisableIntMask(Counter8_4_INT_REG, Counter8_4_INT_MASK)

#endif
// end of file Counter8_4.h
