//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM8_LeftFwd.h
//   Version: 2.60, Updated on 2012/3/2 at 9:15:10
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: PWM8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM8_LeftFwd_INCLUDE
#define PWM8_LeftFwd_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM8_LeftFwd_EnableInt
#pragma fastcall16 PWM8_LeftFwd_DisableInt
#pragma fastcall16 PWM8_LeftFwd_Start
#pragma fastcall16 PWM8_LeftFwd_Stop
#pragma fastcall16 PWM8_LeftFwd_bReadCounter              // Read  DR0
#pragma fastcall16 PWM8_LeftFwd_WritePeriod               // Write DR1
#pragma fastcall16 PWM8_LeftFwd_bReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM8_LeftFwd_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bPWM8_LeftFwd_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bPWM8_LeftFwd_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM8_LeftFwd API.
//-------------------------------------------------

extern void PWM8_LeftFwd_EnableInt(void);                        // Proxy Class 1
extern void PWM8_LeftFwd_DisableInt(void);                       // Proxy Class 1
extern void PWM8_LeftFwd_Start(void);                            // Proxy Class 1
extern void PWM8_LeftFwd_Stop(void);                             // Proxy Class 1
extern BYTE PWM8_LeftFwd_bReadCounter(void);                     // Proxy Class 2
extern void PWM8_LeftFwd_WritePeriod(BYTE bPeriod);              // Proxy Class 1
extern BYTE PWM8_LeftFwd_bReadPulseWidth(void);                  // Proxy Class 1
extern void PWM8_LeftFwd_WritePulseWidth(BYTE bPulseWidth);      // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bPWM8_LeftFwd_ReadCounter(void);            // Deprecated
extern BYTE bPWM8_LeftFwd_ReadPulseWidth(void);         // Deprecated


//--------------------------------------------------
// Constants for PWM8_LeftFwd API's.
//--------------------------------------------------

#define PWM8_LeftFwd_CONTROL_REG_START_BIT     ( 0x01 )
#define PWM8_LeftFwd_INT_REG_ADDR              ( 0x0df )
#define PWM8_LeftFwd_INT_MASK                  ( 0x08 )


//--------------------------------------------------
// Constants for PWM8_LeftFwd user defined values
//--------------------------------------------------

#define PWM8_LeftFwd_PERIOD                    ( 0xff )
#define PWM8_LeftFwd_PULSE_WIDTH               ( 0x00 )


//-------------------------------------------------
// Register Addresses for PWM8_LeftFwd
//-------------------------------------------------

#pragma ioport  PWM8_LeftFwd_COUNTER_REG:   0x04c          //DR0 Count register
BYTE            PWM8_LeftFwd_COUNTER_REG;
#pragma ioport  PWM8_LeftFwd_PERIOD_REG:    0x04d          //DR1 Period register
BYTE            PWM8_LeftFwd_PERIOD_REG;
#pragma ioport  PWM8_LeftFwd_COMPARE_REG:   0x04e          //DR2 Compare register
BYTE            PWM8_LeftFwd_COMPARE_REG;
#pragma ioport  PWM8_LeftFwd_CONTROL_REG:   0x04f          //Control register
BYTE            PWM8_LeftFwd_CONTROL_REG;
#pragma ioport  PWM8_LeftFwd_FUNC_REG:  0x14c              //Function register
BYTE            PWM8_LeftFwd_FUNC_REG;
#pragma ioport  PWM8_LeftFwd_INPUT_REG: 0x14d              //Input register
BYTE            PWM8_LeftFwd_INPUT_REG;
#pragma ioport  PWM8_LeftFwd_OUTPUT_REG:    0x14e          //Output register
BYTE            PWM8_LeftFwd_OUTPUT_REG;
#pragma ioport  PWM8_LeftFwd_INT_REG:       0x0df          //Interrupt Mask Register
BYTE            PWM8_LeftFwd_INT_REG;


//-------------------------------------------------
// PWM8_LeftFwd Macro 'Functions'
//-------------------------------------------------

#define PWM8_LeftFwd_Start_M \
   PWM8_LeftFwd_CONTROL_REG |=  PWM8_LeftFwd_CONTROL_REG_START_BIT

#define PWM8_LeftFwd_Stop_M  \
   PWM8_LeftFwd_CONTROL_REG &= ~PWM8_LeftFwd_CONTROL_REG_START_BIT

#define PWM8_LeftFwd_EnableInt_M   \
   M8C_EnableIntMask(PWM8_LeftFwd_INT_REG, PWM8_LeftFwd_INT_MASK)

#define PWM8_LeftFwd_DisableInt_M  \
   M8C_DisableIntMask(PWM8_LeftFwd_INT_REG, PWM8_LeftFwd_INT_MASK)

#endif
// end of file PWM8_LeftFwd.h
