//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM8_LF.h
//   Version: 2.60, Updated on 2012/3/2 at 9:15:10
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: PWM8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM8_LF_INCLUDE
#define PWM8_LF_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM8_LF_EnableInt
#pragma fastcall16 PWM8_LF_DisableInt
#pragma fastcall16 PWM8_LF_Start
#pragma fastcall16 PWM8_LF_Stop
#pragma fastcall16 PWM8_LF_bReadCounter              // Read  DR0
#pragma fastcall16 PWM8_LF_WritePeriod               // Write DR1
#pragma fastcall16 PWM8_LF_bReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM8_LF_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bPWM8_LF_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bPWM8_LF_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM8_LF API.
//-------------------------------------------------

extern void PWM8_LF_EnableInt(void);                        // Proxy Class 1
extern void PWM8_LF_DisableInt(void);                       // Proxy Class 1
extern void PWM8_LF_Start(void);                            // Proxy Class 1
extern void PWM8_LF_Stop(void);                             // Proxy Class 1
extern BYTE PWM8_LF_bReadCounter(void);                     // Proxy Class 2
extern void PWM8_LF_WritePeriod(BYTE bPeriod);              // Proxy Class 1
extern BYTE PWM8_LF_bReadPulseWidth(void);                  // Proxy Class 1
extern void PWM8_LF_WritePulseWidth(BYTE bPulseWidth);      // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bPWM8_LF_ReadCounter(void);            // Deprecated
extern BYTE bPWM8_LF_ReadPulseWidth(void);         // Deprecated


//--------------------------------------------------
// Constants for PWM8_LF API's.
//--------------------------------------------------

#define PWM8_LF_CONTROL_REG_START_BIT          ( 0x01 )
#define PWM8_LF_INT_REG_ADDR                   ( 0x0df )
#define PWM8_LF_INT_MASK                       ( 0x08 )


//--------------------------------------------------
// Constants for PWM8_LF user defined values
//--------------------------------------------------

#define PWM8_LF_PERIOD                         ( 0xff )
#define PWM8_LF_PULSE_WIDTH                    ( 0xff )


//-------------------------------------------------
// Register Addresses for PWM8_LF
//-------------------------------------------------

#pragma ioport  PWM8_LF_COUNTER_REG:    0x04c              //DR0 Count register
BYTE            PWM8_LF_COUNTER_REG;
#pragma ioport  PWM8_LF_PERIOD_REG: 0x04d                  //DR1 Period register
BYTE            PWM8_LF_PERIOD_REG;
#pragma ioport  PWM8_LF_COMPARE_REG:    0x04e              //DR2 Compare register
BYTE            PWM8_LF_COMPARE_REG;
#pragma ioport  PWM8_LF_CONTROL_REG:    0x04f              //Control register
BYTE            PWM8_LF_CONTROL_REG;
#pragma ioport  PWM8_LF_FUNC_REG:   0x14c                  //Function register
BYTE            PWM8_LF_FUNC_REG;
#pragma ioport  PWM8_LF_INPUT_REG:  0x14d                  //Input register
BYTE            PWM8_LF_INPUT_REG;
#pragma ioport  PWM8_LF_OUTPUT_REG: 0x14e                  //Output register
BYTE            PWM8_LF_OUTPUT_REG;
#pragma ioport  PWM8_LF_INT_REG:       0x0df               //Interrupt Mask Register
BYTE            PWM8_LF_INT_REG;


//-------------------------------------------------
// PWM8_LF Macro 'Functions'
//-------------------------------------------------

#define PWM8_LF_Start_M \
   PWM8_LF_CONTROL_REG |=  PWM8_LF_CONTROL_REG_START_BIT

#define PWM8_LF_Stop_M  \
   PWM8_LF_CONTROL_REG &= ~PWM8_LF_CONTROL_REG_START_BIT

#define PWM8_LF_EnableInt_M   \
   M8C_EnableIntMask(PWM8_LF_INT_REG, PWM8_LF_INT_MASK)

#define PWM8_LF_DisableInt_M  \
   M8C_DisableIntMask(PWM8_LF_INT_REG, PWM8_LF_INT_MASK)

#endif
// end of file PWM8_LF.h
